---
title: "Exploratory_Code"
output: html_notebook
---

### Investigate vanilla

```{r}
all_data %>%
  #filter(surprisal < 15, surprisal > 0) %>%
  filter(model == "vanilla") %>% 
  ggplot(aes(x=surprisal, y=psychometric)) +
    #stat_smooth(se=T, alpha=0.5) +
    #geom_errorbar(color="black", width=.2, position=position_dodge(width=.9), alpha=0.3) +
    geom_point(alpha=0.1) + #stat="identity", position="dodge", alpha=1, size=3) +
    ylab("Processing Time (ms)") +
    xlab("Surprisal (bits)") +
    ggtitle("Surprisal vs. Reading Time / Gaze Duration: Vanilla") +
    facet_grid(corpus~training, scales = "free")
    # scale_color_manual(values = c("bllip-lg"="#440154FF",
    #                           "bllip-md"="#39568CFF",
    #                           "bllip-sm"="#1F968BFF",
    #                           "bllip-xs"="#73D055FF",
    #                           "bllip-lg-gptbpe"="#888888",
    #                           "bllip-md-gptbpe"="#888888",
    #                           "bllip-sm-gptbpe"="#888888",
    #                           "bllip-xs-gptbpe"="#888888"))
```

```{r Tony Blair is the source of that right-side dip}
all_data %>% 
  filter(corpus == "dundee", model == "vanilla", training == "bllip-lg", surprisal > 20, psychometric < 300)
```

```{r}
print(full_residuals %>% filter(corpus == "dundee", model == "vanilla", training == "bllip-lg") %>% arrange(desc(resid)))
full_residuals %>% filter(corpus == "dundee", model == "vanilla", training == "bllip-lg") %>% arrange(desc(resid)) %>% filter(resid > 150) %>% 
  ggplot(aes(x=surprisal)) + geom_density()
```


### Investigate RNNG

```{r}
all_data %>%
  #filter(surprisal < 15, surprisal > 0) %>%
  filter(model == "rnng") %>% 
  ggplot(aes(x=surprisal, y=psychometric)) +
    #stat_smooth(se=T, alpha=0.5) +
    #geom_errorbar(color="black", width=.2, position=position_dodge(width=.9), alpha=0.3) +
    geom_point(alpha=0.1) + #stat="identity", position="dodge", alpha=1, size=3) +
    ylab("Processing Time (ms)") +
    xlab("Surprisal (bits)") +
    ggtitle("Surprisal vs. Reading Time / Gaze Duration: RNNG") +
    facet_grid(corpus~training, scales = "free")
```

```{r Tony Blair is the source of that right-side dip for RNNG too}
all_data %>% 
  filter(corpus == "dundee", model == "rnng", training == "bllip-lg", surprisal > 20, psychometric < 300)
```

```{r}
print(full_residuals %>% filter(corpus == "dundee", model == "rnng", training == "bllip-lg") %>% arrange(desc(resid)))
full_residuals %>% filter(corpus == "dundee", model == "rnng", training == "bllip-lg") %>% arrange(desc(resid)) %>% filter(resid > 150) %>% 
  ggplot(aes(x=surprisal)) + geom_density()
```

### Investigate ngram vs vanilla

```{r}
ngram_resids = full_residuals %>% filter(model == "5gram", training == "bllip-sm") %>% group_by(corpus, code) %>% summarise(freq=mean(freq), psychometric=mean(psychometric), surprisal=mean(surprisal), resid=mean(resid))
vanilla_resids = full_residuals %>% filter(model == "vanilla", training == "bllip-sm") %>% group_by(corpus, code) %>% summarise(freq=mean(freq), psychometric=mean(psychometric), surprisal=mean(surprisal),  resid=mean(resid))
resids_joined = ngram_resids %>% left_join(vanilla_resids, by=c("corpus", "code"), suffix=c(".ngram", ".vanilla"))

resids_joined %>% 
  ggplot(aes(x=resid.ngram, y=resid.vanilla)) + geom_point() + geom_abline(slope=1, color="red") +
  facet_grid(~corpus)

resids_joined %>% 
  mutate(resid_diff=resid.ngram - resid.vanilla) %>% 
  ggplot(aes(x=resid_diff)) + geom_density() +
  facet_grid(~corpus)

resids_joined %>% 
  mutate(resid_diff=abs(resid.ngram) - abs(resid.vanilla),
         big=resid_diff < -10) %>% 
  ggplot(aes(x=surprisal.ngram, color=big)) + geom_density() + facet_grid(~corpus) +
  ggtitle("ngram surprisal of high-improvement tokens (relative to vanilla)")

resids_joined %>% 
  mutate(resid_abs_diff=abs(resid.ngram - resid.vanilla)) %>% 
  ggplot(aes(x=freq.ngram, y=resid_abs_diff)) + geom_point(alpha=0.1) + geom_smooth()
```

### Investigate gptbpe vs vanilla

```{r}
gpt_resids = full_residuals %>% filter(model == "gpt2", training == "bllip-sm-gptbpe") %>% group_by(corpus, code) %>% summarise(freq=mean(freq), psychometric=mean(psychometric), surprisal=mean(surprisal),  resid=mean(resid))
vanilla_resids = full_residuals %>% filter(model == "vanilla", training == "bllip-sm") %>% group_by(corpus, code) %>% summarise(freq=mean(freq), psychometric=mean(psychometric), surprisal=mean(surprisal),  resid=mean(resid))
resids_joined = gpt_resids %>% left_join(vanilla_resids, by=c("corpus", "code"), suffix=c(".gpt", ".vanilla"))

resids_joined %>% 
  ggplot(aes(x=resid.gpt, y=resid.vanilla)) + geom_point() + geom_abline(slope=1, color="red") +
  facet_grid(~corpus)

resids_joined %>% 
  mutate(resid_diff=resid.gpt - resid.vanilla) %>% 
  ggplot(aes(x=resid_diff)) + geom_density() +
  facet_grid(~corpus)

resids_joined %>% 
  mutate(resid_diff=abs(resid.gpt) - abs(resid.vanilla),
         big=resid_diff < -10) %>% 
  ggplot(aes(x=surprisal.gpt, color=big)) + geom_density() + facet_grid(~corpus) +
  ggtitle("gpt surprisal of high-improvement tokens (relative to vanilla)")

resids_joined %>% 
  mutate(resid_abs_diff=abs(resid.gpt - resid.vanilla)) %>% 
  ggplot(aes(x=freq.gpt, y=resid_abs_diff)) + geom_point(alpha=0.1) + geom_smooth()
```

### Investigate residuals overall

```{r}
resid_deltas = full_residuals %>% right_join(baseline_residuals, by=c("corpus", "code", "model", "training", "seed"), suffix=c(".full", ".baseline")) %>%
  select(resid.baseline, resid.full, code, surprisal.full, psychometric.full, model, training, seed, corpus, len.full) %>%
  mutate(resid.baseline.pol = if_else(resid.baseline > 0, 1, 0),
         resid.full.pol = if_else(resid.full > 0, 1, 0)) %>%
  mutate(resid.baseline = abs(resid.baseline),
         resid.full = abs(resid.full)) %>%
  mutate(resid_delta=resid.baseline - resid.full, #positive is better
         training_source=as.factor(str_replace(training, "-gptbpe", "")),
         bpe=str_detect(training, "gptbpe"))
```

```{r}

r = resid_deltas %>%
  filter(resid.full.pol != resid.baseline.pol)

```

```{r}
resid_deltas %>%
  ggplot(aes(x=surprisal.full, y=resid_delta, color=training)) +
    facet_grid(model~corpus) +
    geom_point(alpha=0.1, size=0.5)
```

```{r}
language_model_data %>% filter(model == "gpt2")
```

```{r}
resid_deltas %>%
  group_by(corpus) %>%
    mutate(psychometric = scale(psychometric.full)) %>%
  ungroup() %>%
  ggplot(aes(x=psychometric)) +
    theme_bw() +
    geom_density() +
    geom_vline(xintercept = 0, color = "grey") +
    facet_grid(.~corpus) +
    #coord_cartesian(xlim = c(-2, 4)) +
    theme(axis.title.x=element_blank(),
          axis.text.x=element_blank(),
          axis.ticks.x=element_blank())
#ggsave("length.png", width = 8, height = 1)

```

```{r}

log_lik_deltas  %>%
#resid_deltas %>%
  #filter(resid.full.pol == resid.baseline.pol) %>%
  group_by(corpus) %>%
    mutate(psychometric = scale(psychometric)) %>%
  ungroup() %>%
  #filter(psychometric < 4) %>%
  #filter(len.full <= 10) %>%
  ggplot(aes(x = psychometric, y = delta_log_lik, color = model)) +
    theme_bw() +
    facet_grid(. ~ corpus, scales = "free") +
    #geom_rug(alpha = 0.003, sides = "b") +
    geom_hline(yintercept=0, color = "blue") +
    geom_vline(xintercept = 0, color = "grey") +
    geom_smooth(se = T, alpha = 0.2) +
    coord_cartesian(ylim = c(-0.1, 0.2), xlim = c(-2, 4)) +
    theme(legend.position = "bottom",
          strip.text.x = element_blank()) 
ggsave( "./resid_psycho.png", height = 4, width = 8)


```

```{r}
resid_deltas %>%
  group_by(corpus) %>%
    mutate(psychometric = scale(psychometric.full)) %>%
  ungroup() %>%
  ggplot(aes(x=len.full)) +
    theme_bw() +
    geom_histogram(bins = 20) +
    geom_vline(xintercept = 0, color = "grey") +
    facet_grid(.~corpus) +
    coord_cartesian(xlim = c(1, 10)) +
    theme(axis.title.x=element_blank(),
          axis.text.x=element_blank(),
          axis.ticks.x=element_blank())
ggsave("length_maringals.png", width = 8, height = 1)
```

```{r}

log_lik_deltas  %>%
#resid_deltas %>%
  #filter(resid.full.pol == resid.baseline.pol) %>%
  group_by(corpus) %>%
    mutate(psychometric = scale(psychometric)) %>%
  ungroup() %>%
  #filter(psychometric < 4) %>%
  #filter(len.full <= 10) %>%
  ggplot(aes(x = len, y = delta_log_lik, color = model)) +
    theme_bw() +
    facet_grid(. ~ corpus, scales = "free") +
    #geom_rug(alpha = 0.003, sides = "b") +
    geom_hline(yintercept=0, color = "blue") +
    geom_vline(xintercept = 0, color = "grey") +
    geom_smooth(se = T, alpha = 0.2) +
    coord_cartesian(ylim = c(-0.02, 0.06), xlim = c(1, 10)) +
    theme(legend.position = "bottom",
          strip.text.x = element_blank()) 
ggsave( "./resid_length.png", height = 4, width = 8)
```


```{r}

word_norm = log_lik_deltas %>%
  drop_na() %>%
  group_by(word, corpus, model, training, seed) %>% 
  mutate(psychoword = scale(psychometric),
         norm_surp = scale(surprisal))
```

```{r}
word_norm %>%
  ggplot(aes(x=norm_surp)) +
  facet_grid(~corpus) +
  geom_density() +
  coord_cartesian(xlim = c(-2, 5)) +
  geom_vline(xintercept = 0, color = "grey") +
  theme_bw() +
    theme(axis.title.x=element_blank(),
          axis.text.x=element_blank(),
          axis.ticks.x=element_blank())
ggsave("surp_maringals.png", width = 8, height = 1)


```
```{r}

word_norm %>%
  ggplot(aes(x = psychoword, y = norm_surp, color = model)) +
    theme_bw() +
    facet_grid(. ~ corpus, scales = "free") +
    #geom_rug(alpha = 0.003, sides = "b") +
    geom_hline(yintercept=0, color = "blue") +
    geom_vline(xintercept = 0, color = "grey") +
    geom_smooth(se = T, alpha = 0.2) +
    #coord_cartesian(ylim = c(-0.05, 0.1), xlim = c(-2, 3)) +
    theme(legend.position = "bottom") 
#ggsave( "./resid_length.png", height = 4, width = 8)

```

```{r}

word_norm %>%
  ggplot(aes(x = norm_surp, y = delta_log_lik, color = model)) +
    theme_bw() +
    facet_grid( . ~ corpus, scales = "free") +
    #geom_rug(alpha = 0.003, sides = "b") +
    geom_hline(yintercept=0, color = "blue") +
    geom_vline(xintercept = 0, color = "grey") +
    geom_smooth(se = T, alpha = 0.2) +
    coord_cartesian(ylim = c(-0.05, 0.07), xlim = c(-2, 5)) +
    theme(legend.position = "bottom") 
ggsave( "./norm_surp.png", height = 4, width = 8)

```

```{r}

ngram_highsurp = word_norm %>%
  ungroup() %>%
  filter(corpus == "dundee", norm_surp > 2, model == "5gram") %>%
  select(code)

ngram_highsurp = ngram_highsurp$code

z = word_norm %>%
  ungroup() %>%
  filter(! code %in% ngram_highsurp) %>%
  filter(corpus == "dundee")

write.csv(z, "ngram-ablate.csv")

```

